server:
  port: 8181
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #连接池的类型
    username: root
    password: 123456sd
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recycle?serverTimezone=GMT
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
